# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1171, 771))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(490, 50, 681, 571))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.Canada))
        self.textBrowser.setObjectName("textBrowser")
        self.labelChapitre = QtWidgets.QLabel(self.frame)
        self.labelChapitre.setGeometry(QtCore.QRect(490, 0, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelChapitre.setFont(font)
        self.labelChapitre.setObjectName("labelChapitre")
        self.listObjets = QtWidgets.QListWidget(self.frame)
        self.listObjets.setGeometry(QtCore.QRect(10, 50, 381, 121))
        self.listObjets.setObjectName("listObjets")
        item = QtWidgets.QListWidgetItem()
        self.listObjets.addItem(item)
        self.listObjetsSpeciaux = QtWidgets.QListWidget(self.frame)
        self.listObjetsSpeciaux.setGeometry(QtCore.QRect(10, 220, 381, 111))
        self.listObjetsSpeciaux.setObjectName("listObjetsSpeciaux")
        item = QtWidgets.QListWidgetItem()
        self.listObjetsSpeciaux.addItem(item)
        self.listDisciplines = QtWidgets.QListWidget(self.frame)
        self.listDisciplines.setGeometry(QtCore.QRect(10, 350, 381, 161))
        self.listDisciplines.setObjectName("listDisciplines")
        item = QtWidgets.QListWidgetItem()
        self.listDisciplines.addItem(item)
        self.pushLienPDF = QtWidgets.QPushButton(self.frame)
        self.pushLienPDF.setGeometry(QtCore.QRect(10, 660, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushLienPDF.setFont(font)
        self.pushLienPDF.setObjectName("pushLienPDF")
        self.textEditCombat = QtWidgets.QTextEdit(self.frame)
        self.textEditCombat.setGeometry(QtCore.QRect(490, 660, 681, 101))
        self.textEditCombat.setObjectName("textEditCombat")
        self.textEditEndurance = QtWidgets.QTextEdit(self.frame)
        self.textEditEndurance.setGeometry(QtCore.QRect(340, 660, 121, 101))
        self.textEditEndurance.setObjectName("textEditEndurance")
        self.textEditHabilete = QtWidgets.QTextEdit(self.frame)
        self.textEditHabilete.setGeometry(QtCore.QRect(200, 660, 121, 101))
        self.textEditHabilete.setObjectName("textEditHabilete")
        self.listArmes = QtWidgets.QListWidget(self.frame)
        self.listArmes.setGeometry(QtCore.QRect(10, 530, 381, 101))
        self.listArmes.setObjectName("listArmes")
        item = QtWidgets.QListWidgetItem()
        self.listArmes.addItem(item)
        self.pushSave = QtWidgets.QPushButton(self.frame)
        self.pushSave.setGeometry(QtCore.QRect(10, 720, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushSave.setFont(font)
        self.pushSave.setObjectName("pushSave")
        self.comboBoxPagesSuivantes = QtWidgets.QComboBox(self.frame)
        self.comboBoxPagesSuivantes.setGeometry(QtCore.QRect(589, 630, 71, 22))
        self.comboBoxPagesSuivantes.setObjectName("comboBoxPagesSuivantes")
        self.labelAllerPage = QtWidgets.QLabel(self.frame)
        self.labelAllerPage.setGeometry(QtCore.QRect(490, 630, 101, 21))
        self.labelAllerPage.setObjectName("labelAllerPage")
        self.pushButtonTournerPage = QtWidgets.QPushButton(self.frame)
        self.pushButtonTournerPage.setGeometry(QtCore.QRect(680, 630, 75, 23))
        self.pushButtonTournerPage.setObjectName("pushButtonTournerPage")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Le texte du chapitre</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p></body></html>"))
        self.labelChapitre.setText(_translate("MainWindow", "Chapitre x"))
        __sortingEnabled = self.listObjets.isSortingEnabled()
        self.listObjets.setSortingEnabled(False)
        item = self.listObjets.item(0)
        item.setText(_translate("MainWindow", "Liste objets + Repas?"))
        self.listObjets.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listObjetsSpeciaux.isSortingEnabled()
        self.listObjetsSpeciaux.setSortingEnabled(False)
        item = self.listObjetsSpeciaux.item(0)
        item.setText(_translate("MainWindow", "Liste objets spéciaux"))
        self.listObjetsSpeciaux.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listDisciplines.isSortingEnabled()
        self.listDisciplines.setSortingEnabled(False)
        item = self.listDisciplines.item(0)
        item.setText(_translate("MainWindow", "Liste disciplines"))
        self.listDisciplines.setSortingEnabled(__sortingEnabled)
        self.pushLienPDF.setText(_translate("MainWindow", "Lien vers pdf?"))
        self.textEditCombat.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Combat</span></p></body></html>"))
        self.textEditEndurance.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Endurance</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.textEditHabilete.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Habileté</span></p></body></html>"))
        __sortingEnabled = self.listArmes.isSortingEnabled()
        self.listArmes.setSortingEnabled(False)
        item = self.listArmes.item(0)
        item.setText(_translate("MainWindow", "Armes"))
        self.listArmes.setSortingEnabled(__sortingEnabled)
        self.pushSave.setText(_translate("MainWindow", "Sauvegarder"))
        self.labelAllerPage.setText(_translate("MainWindow", "Aller à la page"))
        self.pushButtonTournerPage.setText(_translate("MainWindow", "Tourner page"))
