# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pop_up(object):
    def setupUi(self, pop_up):
        pop_up.setObjectName("pop_up")
        pop_up.resize(769, 366)
        self.comboBoxLivre = QtWidgets.QComboBox(pop_up)
        self.comboBoxLivre.setGeometry(QtCore.QRect(260, 120, 461, 31))
        self.comboBoxLivre.setObjectName("comboBoxLivre")
        self.boutonNouvellePartie = QtWidgets.QPushButton(pop_up)
        self.boutonNouvellePartie.setGeometry(QtCore.QRect(40, 120, 201, 31))
        self.boutonNouvellePartie.setObjectName("boutonNouvellePartie")
        self.labelBienvenu = QtWidgets.QLabel(pop_up)
        self.labelBienvenu.setGeometry(QtCore.QRect(30, 10, 671, 81))
        font = QtGui.QFont()
        font.setPointSize(33)
        self.labelBienvenu.setFont(font)
        self.labelBienvenu.setObjectName("labelBienvenu")
        self.comboBoxSave = QtWidgets.QComboBox(pop_up)
        self.comboBoxSave.setGeometry(QtCore.QRect(260, 160, 461, 31))
        self.comboBoxSave.setObjectName("comboBoxSave")
        self.boutonPartieSave = QtWidgets.QPushButton(pop_up)
        self.boutonPartieSave.setGeometry(QtCore.QRect(40, 160, 201, 31))
        self.boutonPartieSave.setObjectName("boutonPartieSave")
        self.boutonQuitter = QtWidgets.QPushButton(pop_up)
        self.boutonQuitter.setGeometry(QtCore.QRect(240, 280, 271, 41))
        self.boutonQuitter.setObjectName("boutonQuitter")
        self.boutonPartieSupprimer = QtWidgets.QPushButton(pop_up)
        self.boutonPartieSupprimer.setEnabled(False)
        self.boutonPartieSupprimer.setGeometry(QtCore.QRect(40, 200, 201, 31))
        self.boutonPartieSupprimer.setObjectName("boutonPartieSupprimer")

        self.retranslateUi(pop_up)
        QtCore.QMetaObject.connectSlotsByName(pop_up)

    def retranslateUi(self, pop_up):
        _translate = QtCore.QCoreApplication.translate
        pop_up.setWindowTitle(_translate("pop_up", "Un livre dont vous êtes le héro"))
        self.boutonNouvellePartie.setText(_translate("pop_up", "Nouvelle Partie"))
        self.labelBienvenu.setText(_translate("pop_up", "Bienvenu loup solitaire"))
        self.boutonPartieSave.setText(_translate("pop_up", "Partie Sauvegardée"))
        self.boutonQuitter.setText(_translate("pop_up", "Quitter"))
        self.boutonPartieSupprimer.setText(_translate("pop_up", "Supprimer partie"))
